# Generated by Django 5.2.7 on 2025-11-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincatch', '0002_pagegroup_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('br', 'Brazilian Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('ru', 'Russian'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('it', 'Italian'), ('uk', 'Ukrainian'), ('ko', 'Korean'), ('ja', 'Japanese'), ('zh-hans', 'Chinese Simplified')], default='en', help_text='Language for this page instance.', max_length=10),
        ),
    ]
