# Generated by Django 5.2.7 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincatch', '0005_slug_url_and_optional_group'),
    ]

    def _populate_language_slug(apps, schema_editor):
        Page = apps.get_model('pincatch', 'Page')
        for page in Page.objects.all():
            if not page.language_slug:
                page.language_slug = page.language
                page.save(update_fields=['language_slug'])

    operations = [
        migrations.AddField(
            model_name='page',
            name='language_slug',
            field=models.CharField(blank=True, help_text="Final URL segment for this page's language (defaults to the language code).", max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug_url',
            field=models.CharField(help_text="Path component without language, e.g., 'url-downloader'", max_length=255),
        ),
        migrations.RunPython(_populate_language_slug, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('slug_url', 'language_slug'), name='uniq_page_url_per_language_slug'),
        ),
    ]
