# Generated by Django 5.2.7 on 2025-11-19 16:50

import os
from django.conf import settings
from django.db import migrations


TEMPLATE_CONTENT = """{% extends "index.html" %}
{% load i18n %}

{% block title %}{{ meta_title }}{% endblock %}

{% block meta_description %}{{ meta_description }}{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <div class="max-w-4xl mx-auto">
        <h1 class="text-3xl font-bold mb-6">{{ page_title }}</h1>
        <div class="prose prose-lg max-w-none">
            {{ content|safe }}
        </div>
    </div>
</div>
{% endblock %}
"""


class Migration(migrations.Migration):

    dependencies = [
        ('pincatch', '0006_page_language_slug_alter_page_slug_url_and_more'),
    ]

    def _ensure_templates(apps, schema_editor):
        Page = apps.get_model('pincatch', 'Page')
        for page in Page.objects.all():
            slug = page.slug_url
            language_slug = getattr(page, 'language_slug', '') or page.language
            template_dir = os.path.join(settings.BASE_DIR, 'templates', slug)
            os.makedirs(template_dir, exist_ok=True)
            template_path = os.path.join(template_dir, f"{language_slug}.html")
            if os.path.isfile(template_path):
                continue
            fallback_old = os.path.join(template_dir, f"{page.language}.html")
            if os.path.isfile(fallback_old):
                os.rename(fallback_old, template_path)
                continue
            with open(template_path, 'w', encoding='utf-8') as f:
                f.write(TEMPLATE_CONTENT)

    operations = [
        migrations.RunPython(_ensure_templates, migrations.RunPython.noop),
    ]
