# Generated by Django 5.2.7 on 2025-11-19 18:16

from django.db import migrations


def _normalize_slug(value, fallback):
    if not value:
        return fallback
    normalized = value.strip().strip('/')
    if '/' in normalized:
        normalized = normalized.split('/')[0]
    return normalized or fallback


def _normalize(apps, schema_editor):
    Page = apps.get_model('pincatch', 'Page')
    PageGroup = apps.get_model('pincatch', 'PageGroup')
    fields_to_copy = ["name", "meta_title", "meta_description", "content"]

    for page in Page.objects.select_related('group'):
        normalized = _normalize_slug(page.slug_url, f"page-{page.pk}")
        if normalized == page.slug_url:
            if page.group_id and page.group.slug_url != normalized:
                PageGroup.objects.filter(pk=page.group_id).update(slug_url=normalized)
            continue

        conflict = (
            Page.objects.filter(slug_url=normalized, language=page.language)
            .exclude(pk=page.pk)
            .order_by('-last_modified')
            .first()
        )

        if conflict:
            # Keep the most recently updated record's content
            if conflict.last_modified < page.last_modified:
                for field in fields_to_copy:
                    setattr(conflict, field, getattr(page, field))
                if not getattr(conflict, "language_slug", None):
                    conflict.language_slug = getattr(page, "language_slug", None) or page.language
                conflict.save()
            page.delete()
            continue

        page.slug_url = normalized
        page.save()
        if page.group_id and page.group.slug_url != normalized:
            PageGroup.objects.filter(pk=page.group_id).update(slug_url=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('pincatch', '0007_ensure_templates'),
    ]

    operations = [
        migrations.RunPython(_normalize, migrations.RunPython.noop),
    ]
