"""
Django settings for pinit project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_env(name, default=None, required=False):
    value = os.environ.get(name, default)
    if required and value in (None, ""):
        raise ImproperlyConfigured(f"{name} is required")
    return value


def get_env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def normalise_path(value, fallback):
    candidate = (value or fallback).strip("/")
    return f"{candidate}/" if candidate else fallback


def rosetta_access_control(user):
    return user.is_authenticated and user.is_staff


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DJANGO_DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env("DJANGO_SECRET_KEY", None)
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "insecure-development-secret"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY is required")

allowed_hosts_value = get_env("DJANGO_ALLOWED_HOSTS", None)
if allowed_hosts_value:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_value.split(",") if host.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
else:
    raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS is required")

csrf_trusted_value = get_env("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted_value.split(",") if origin.strip()]


# Application definition

INSTALLED_APPS = [
    "blog.apps.BlogConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'pinit',
    "rosetta",
    "django_restful_translator",
    "django_social_share",
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "js_asset.context_processors.importmap",
            ],
        },
    },
]

WSGI_APPLICATION = 'pinit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    # ('bn', _('Bengali')),   #Not supported by DeepL
    # ('fil', _('Filipino')),   #Not supported by DeepL
    # ('az', _('Azerbaijani')), #Not supported by DeepL
    ('br', _('Brazilian Portuguese')),
    ('de', _('German')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('ru', _('Russian')),
    ('ar', _('Arabic')),
    # ('vi', _('Vietnamese')),  #Not supported by DeepL
    ('pt', _('Portuguese')),
    ('tr', _('Turkish')),
    ('id', _('Indonesian')),
    ('it', _('Italian')),
    ('uk', _('Ukrainian')),
    # ('ne', _('Nepali')),    #Not supported by DeepL
    ('ko', _('Korean')),
    ('ja', _('Japanese')),
    ('zh-hans', _('Chinese Simplified')),
    # ('zh-hant', _('Chinese Traditional')),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
    BASE_DIR / "drt_locale",
]

LANGUAGE_BIDI = True # Languages that are written right to left (like Arabic, Hebrew, etc.

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For production use with collectstatic
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
    # or os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_ID = 1
MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEEPL_AUTH_KEY = get_env("DEEPL_AUTH_KEY", "")
if not DEEPL_AUTH_KEY and not DEBUG:
    raise ImproperlyConfigured("DEEPL_AUTH_KEY is required")

ADMIN_URL = normalise_path(get_env("DJANGO_ADMIN_URL", "admin/"), "admin/")
ROSETTA_URL = normalise_path(get_env("DJANGO_ROSETTA_URL", "rosetta/"), "rosetta/")

ROSETTA_LOGIN_REQUIRED = True
ROSETTA_ACCESS_CONTROL_FUNCTION = "pinit.settings.rosetta_access_control"

CKEDITOR_UPLOAD_PATH = 'uploads/'