# Generated by Django 5.2.7 on 2025-10-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30, unique=True)),
                ('name_en', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_bn', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_az', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_pt_br', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_de', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_es', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_fr', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_ru', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_ar', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_vi', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_pt', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_tr', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_ind', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_it', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_uk', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_ne', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_ko', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_ja', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_zh_hans', models.CharField(default='None', max_length=30, null=True, unique=True)),
                ('name_zh_hant', models.CharField(default='None', max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=255)),
                ('title_en', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_bn', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_az', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_pt_br', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_de', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_es', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_fr', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_ru', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_ar', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_vi', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_pt', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_tr', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_ind', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_it', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_uk', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_ne', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_ko', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_ja', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_zh_hans', models.CharField(default='No Title', max_length=255, null=True)),
                ('title_zh_hant', models.CharField(default='No Title', max_length=255, null=True)),
                ('body', models.TextField(default='none')),
                ('body_en', models.TextField(default='none', null=True)),
                ('body_bn', models.TextField(default='none', null=True)),
                ('body_az', models.TextField(default='none', null=True)),
                ('body_pt_br', models.TextField(default='none', null=True)),
                ('body_de', models.TextField(default='none', null=True)),
                ('body_es', models.TextField(default='none', null=True)),
                ('body_fr', models.TextField(default='none', null=True)),
                ('body_ru', models.TextField(default='none', null=True)),
                ('body_ar', models.TextField(default='none', null=True)),
                ('body_vi', models.TextField(default='none', null=True)),
                ('body_pt', models.TextField(default='none', null=True)),
                ('body_tr', models.TextField(default='none', null=True)),
                ('body_ind', models.TextField(default='none', null=True)),
                ('body_it', models.TextField(default='none', null=True)),
                ('body_uk', models.TextField(default='none', null=True)),
                ('body_ne', models.TextField(default='none', null=True)),
                ('body_ko', models.TextField(default='none', null=True)),
                ('body_ja', models.TextField(default='none', null=True)),
                ('body_zh_hans', models.TextField(default='none', null=True)),
                ('body_zh_hant', models.TextField(default='none', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.category')),
            ],
        ),
    ]
