# Generated by Django 5.2.7 on 2025-10-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_created_on_category_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='no-slug', max_length=255, unique=True),
        ),
    ]
