# Generated by Django 5.2.6 on 2025-11-15 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_redirect_url', models.URLField(blank=True, help_text='URL to redirect homepage to (for DMCA protection). Leave empty to disable redirect.', max_length=500, null=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable homepage redirect')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
