# Generated by Django 5.2.7 on 2025-11-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default='Meta Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(default='Meta Title'),
        ),
    ]
